In [20]:
# import packages
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Data loading and observing

In [3]:
# load the data
dataset = pd.read_csv('life_expectancy.csv')

dataset.head() # observe first few rows of the data

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,Afghanistan,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,Afghanistan,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,Afghanistan,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,Afghanistan,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,Afghanistan,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2

In [4]:
dataset.describe() # see summary statistics

,Year,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
count,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2.938000e+03,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000
mean,2007.518720,164.725664,30.303948,4.546875,738.251295,83.022124,2419.592240,38.381178,42.035739,82.617767,5.924098,82.393125,1.742103,6611.523863,1.023085e+07,4.821886,4.852144,0.630362,12.009837,69.234717
std,4.613841,124.086215,117.926501,3.921946,1987.914858,22.996984,11467.272489,19.935375,160.445548,23.367166,2.400770,23.655562,5.077785,13296.603449,5.402242e+07,4.397621,4.485854,0.205140,3.265139,9.509115
min,2000.000000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,36.300000
25%,2004.000000,74.000000,0.000000,1.092500,4.685343,82.000000,0.000000,19.400000,0.000000,78.000000,4.370000,78.000000,0.100000,580.486996,4.189172e+05,1.600000,1.600000,0.504250,10.300000,63.200000
50%,2008.000000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.755000,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000,72.100000
75%,2012.000000,227.000000,22.000000,7.390000,441.534144,96.000000,360.250000,56.100000,28.000000,97.000000,7.330000,97.000000,0.800000,4779.405190,4.584371e+06,7.100000,7.200000,0.772000,14.100000,75.600000
max,2015.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.600000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000,89.000000

In [5]:
dataset = dataset.drop(['Country'], axis=1) # drop the country column 


# split dataset into labels and features
labels = dataset.iloc[:, -1] #select all the rows (:), and access the last column (-1)

features = dataset.iloc[:, 0:-1] #select all the rows (:), and access columns from 0 to the last column

# Data Preprocessing

In [10]:
features = pd.get_dummies(features) # convert categorical to numerical using one-hot encoding

# split data into training and test sets
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.2, random_state=20)

In [13]:
# standardize
numerical_features = features.select_dtypes(include=['float64', 'int64']) # select all list of numerical data

numerical_columns = numerical_features.columns # set columns

# initializes a ColumnTransformer
ct = ColumnTransformer([("scale", StandardScaler(), numerical_columns)], remainder='passthrough') 

features_train_scaled = ct.fit_transform(features_train) #fit the standadizer to the training data 

features_test_scaled = ct.transform(features_test) #applied the trained standadizer on the test data

# Building the model

In [25]:
# building the model
my_model = Sequential(name = "Country_Life_Expectancy_Prediction")

input = InputLayer(input_shape = (features.shape[1], )) # create input layer
my_model.add(input) # add input layer to model

my_model.add(Dense(64, activation = "relu")) # create and add hidden layer 

my_model.add(Dense(1)) # add output layer with one neuron 4 1 output

# Initializing the optimizer and compiling the model

In [26]:
opt = Adam(learning_rate = 0.01) # initializes an Adam optimizer

my_model.compile(loss='mse',  metrics=['mae'], optimizer=opt) # compile the model

# Fit and evaluate the model

In [28]:
# fit the model
my_model.fit(features_train_scaled, labels_train, epochs = 40, batch_size = 1, verbose = 1)

# evaluate model
res_mse, res_mae = my_model.evaluate(features_test_scaled, labels_test, verbose = 0)

print(my_model.summary()) # print summary of the sequential model

print("MSE: ", res_mse) # print root mean squared errors 

print("MAE: ", res_mae) # print mean absolute errors

Epoch 1/40
2350/2350 [==============================] - 1s 548us/step - loss: 7.4415 - mae: 2.0207
Epoch 2/40
2350/2350 [==============================] - 1s 505us/step - loss: 6.9499 - mae: 1.9229
Epoch 3/40
2350/2350 [==============================] - 1s 504us/step - loss: 6.7873 - mae: 1.9416
Epoch 4/40
2350/2350 [==============================] - 1s 549us/step - loss: 7.1496 - mae: 1.9558
Epoch 5/40
2350/2350 [==============================] - 1s 498us/step - loss: 6.8368 - mae: 1.9236
Epoch 6/40
2350/2350 [==============================] - 1s 539us/step - loss: 6.8477 - mae: 1.9397
Epoch 7/40
2350/2350 [==============================] - 1s 512us/step - loss: 7.5452 - mae: 1.9823
Epoch 8/40
2350/2350 [==============================] - 1s 497us/step - loss: 6.7292 - mae: 1.8963
Epoch 9/40
2350/2350 [==============================] - 1s 497us/step - loss: 7.1524 - mae: 1.9399
Epoch 10/40
2350/2350 [==============================] - 1s 534us/step - loss: 7.2573 - mae: 1.9607
Epoch 11/40
2350/2350 [==============================] - 1s 499us/step - loss: 6.9144 - mae: 1.9233
Epoch 12/40
2350/2350 [==============================] - 1s 492us/step - loss: 6.6062 - mae: 1.8759
Epoch 13/40
2350/2350 [==============================] - 1s 505us/step - loss: 6.9395 - mae: 1.9144
Epoch 14/40
2350/2350 [==============================] - 1s 536us/step - loss: 6.7456 - mae: 1.9216
Epoch 15/40
2350/2350 [==============================] - 1s 502us/step - loss: 7.5142 - mae: 1.8812
Epoch 16/40
2350/2350 [==============================] - 1s 510us/step - loss: 6.6444 - mae: 1.8987
Epoch 17/40
2350/2350 [==============================] - 1s 537us/step - loss: 7.1175 - mae: 1.9322
Epoch 18/40
2350/2350 [==============================] - 1s 510us/step - loss: 6.2195 - mae: 1.8560
Epoch 19/40
2350/2350 [==============================] - 1s 537us/step - loss: 6.8961 - mae: 1.9306
Epoch 20/40
2350/2350 [==============================] - 1s 510us/step - loss: 7.0954 - mae: 1.8989
Epoch 21/40
2350/2350 [==============================] - 1s 493us/step - loss: 6.8936 - mae: 1.8787
Epoch 22/40
2350/2350 [==============================] - 1s 524us/step - loss: 6.4162 - mae: 1.8500
Epoch 23/40
2350/2350 [==============================] - 2s 646us/step - loss: 6.4563 - mae: 1.8736
Epoch 24/40
2350/2350 [==============================] - 1s 504us/step - loss: 6.8504 - mae: 1.9054
Epoch 25/40
2350/2350 [==============================] - 1s 501us/step - loss: 6.8775 - mae: 1.8886
Epoch 26/40
2350/2350 [==============================] - 1s 567us/step - loss: 5.9870 - mae: 1.8217
Epoch 27/40
2350/2350 [==============================] - 1s 563us/step - loss: 7.1003 - mae: 1.9287
Epoch 28/40
2350/2350 [==============================] - 1s 519us/step - loss: 6.6311 - mae: 1.8953
Epoch 29/40
2350/2350 [==============================] - 1s 543us/step - loss: 6.6618 - mae: 1.8802
Epoch 30/40
2350/2350 [==============================] - 1s 538us/step - loss: 6.4141 - mae: 1.8751
Epoch 31/40
2350/2350 [==============================] - 1s 563us/step - loss: 6.4062 - mae: 1.8684
Epoch 32/40
2350/2350 [==============================] - 1s 540us/step - loss: 7.0642 - mae: 1.8798
Epoch 33/40
2350/2350 [==============================] - 1s 546us/step - loss: 6.4238 - mae: 1.8428
Epoch 34/40
2350/2350 [==============================] - 1s 564us/step - loss: 6.8996 - mae: 1.9047
Epoch 35/40
2350/2350 [==============================] - 1s 551us/step - loss: 6.7239 - mae: 1.8763
Epoch 36/40
2350/2350 [==============================] - 1s 559us/step - loss: 6.2007 - mae: 1.8304
Epoch 37/40
2350/2350 [==============================] - 1s 561us/step - loss: 6.8361 - mae: 1.9015
Epoch 38/40
2350/2350 [==============================] - 1s 510us/step - loss: 6.4535 - mae: 1.8605
Epoch 39/40
2350/2350 [==============================] - 1s 505us/step - loss: 6.3925 - mae: 1.8575
Epoch 40/40
2350/2350 [==============================] - 1s 530us/step - loss: 6.1954 - mae: 1.8287
Model: "Country_Life_Expectancy_Prediction"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 64)                1408
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 65
=================================================================
Total params: 1,473
Trainable params: 1,473
Non-trainable params: 0
_________________________________________________________________
None
MSE:  7.568733215332031
MAE:  2.0113773345947266